[package]
name = "orion-exchange-elrond"
version = "0.1.0"
authors = ["Willem Olding <willemolding@gmail.com>"]
edition = "2018"

[lib]
path = "src/lib.rs"

[[bin]]
name = "orion-exchange-elrond"
path = "src/lib.rs"

[dependencies]
elrond-wasm = "0.5.1"
elrond-wasm-node = "0.5.1"
elrond-wasm-derive = "0.5.1"

common = { path = "../common" }
